language: cpp

branches:
  only:
    - master
    - model
    - gui-implementation

matrix:
  include:
    - os: osx
      python: 3.7
      osx_image: xcode11.6
      addons:
        homebrew:
          packages:
            - vtk
            - librealsense
            - opencv
            - pcl

dist: trusty

before_install:
  - brew upgrade pcl

install:
  - git clone https://github.com/seanngpack/feeling-blue-cpp
  - cd feeling-blue-cpp
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install


before_script:
#  - brew install vtk
#  - brew install librealsense
#  - brew install --HEAD pcl
#  - brew install opencv
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build

script:
  - cd build
  - cmake -DBUILD_TESTS=ON ..
  - make
  - ctest