language: cpp

branches:
  only:
    - master
    - model-dev
    - gui-overhaul
    - registration-algo-dev

matrix:
  include:
    - os: osx
      python: 3.7
      osx_image: xcode11.6
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/target
          - $HOME/Library/Caches/Homebrew
          - /usr/local/Homebrew
          - $HOME/local_bottle_metadata
      addons:
        homebrew:
          update: true
          packages:
            - vtk
            - librealsense
            - opencv
            - spdlog
            - qt
            - pcl

dist: trusty

# https://gist.github.com/gfreezy/52cb2afe807d59b821c82a50cd183f4b
before_install: |
  if [ -n "$IS_OSX" ]; then
      TAPS="$(brew --repository)/Library/Taps"
      if [ -e "$TAPS/caskroom/homebrew-cask" -a -e "$TAPS/homebrew/homebrew-cask" ]; then
          rm -rf "$TAPS/caskroom/homebrew-cask"
      fi
      find "$TAPS" -type d -name .git -exec \
              bash -xec '
                  cd $(dirname '\''{}'\'') || echo "status: $?"
                  git clean -fxd || echo "status: $?"
                  sleep 1 || echo "status: $?"
                  git status || echo "status: $?"' \; || echo "status: $?"
      brew_cache_cleanup
  fi


before_cache: |
  # Cleanup dirs to be cached
  set -e; set -x
  if [ -n "$IS_OSX" ]; then
      # When Taps is cached, this dir causes "Error: file exists" on `brew update`
      if [ -e "$(brew --repository)/Library/Taps/homebrew/homebrew-cask/homebrew-cask" ]; then
          rm -rf "$(brew --repository)/Library/Taps/homebrew/homebrew-cask/homebrew-cask"
      fi
      brew_cache_cleanup
  fi
  set +x; set +e

#before_install:
#  - brew upgrade pcl

install:
  - git clone https://github.com/seanngpack/feeling-blue-cpp
  - cd feeling-blue-cpp
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install


before_script:
#  - brew install vtk
#  - brew install librealsense
#  - brew install --HEAD pcl
#  - brew install opencv
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build

script:
  - cd build
  - cmake -DBUILD_TESTS=ON ..
  - make
  - ctest
